name = "sub-question-store"
pages_build_output_dir = "dist"
compatibility_date = "2024-04-01"
compatibility_flags = ["nodejs_compat"]

# Cloudflare D1 Database Binding (Connected to Cloudflare Free Tier)
[[d1_databases]]
binding = "DB"
database_name = "sub-question-d1"
database_id = "055c6cf1-5b41-465f-8828-1f16609fe54e"

# Cloudflare R2 Object Storage Bucket Binding (10GB Free Tier)
[[r2_buckets]]
binding = "PAPERS_BUCKET"
bucket_name = "sub-question-r2"

# Environmental Variables
[vars]
ENVIRONMENT = "production"
MAX_UPLOAD_SIZE_BYTES = "25165824" # 24 MB max file upload limit
